version: "3.3"
volumes:
  pgdata:
services:
  test-loan-db:
    restart: always
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_USER: "infocare"
      POSTGRES_DB: "infocare"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./configs/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
  infocare-crawler:
    build:
      context: .
      dockerfile: Dockerfile-infocare-crawler
      args:
        env: local
    command: >
      python manage.py run
    volumes:
      - ./app/infocare-crawler/:/crawler/app/infocare-crawler/
      - ./lib/crawler-python-commons:/crawler/lib/crawler-python-commons
      - ./lib/tanker-python-commons:/crawler/lib/tanker-python-commons
    environment:
      CRAWLER_ENVIRONMENT: local
  infocare-store:
    build:
      context: .
      dockerfile: Dockerfile-infocare-store
      args:
        env: local
    command: >
      python manage.py run
    volumes:
      - ./app/infocare-store/:/store/app/infocare-store/
      - ./lib/crawler-python-commons:/store/lib/crawler-python-commons
      - ./lib/tanker-python-commons:/store/lib/tanker-python-commons
      - ./lib/loan-model:/store/lib/loan-model
    environment:
      STORE_ENVIRONMENT: local
      STORE_AWS_S3_BUCKET_NAME: ${STORE_AWS_S3_BUCKET_NAME}
      STORE_AWS_ACCESS_KEY_ID: ${STORE_AWS_ACCESS_KEY_ID}
      STORE_AWS_SECRET_ACCESS_KEY: ${STORE_AWS_SECRET_ACCESS_KEY}

      STORE_SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://infocare:devpassword@test-loan-db:5432/infocare
    depends_on:
      - test-loan-db